version: '3.1'
services:
  postgres:
    image: bitnami/postgresql:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: orcascan
      POSTGRES_PASSWORD: UHVUOOUSDOFHBKHJVKGHCYTHHgvkusvIHBUVUtvjkjhbbiBIBHouy877987y90ub870bt86T
      POSTGRES_DB: orcascan
  orcascan:
    build: .
    image: orcascan-latest
    env_file:
        - .env
#  redis:
#    image: bitnami/redis:latest
#    restart: always
#    ports:
#      - "6379:6379"
#    environment:
#      - ALLOW_EMPTY_PASSWORD=yes
